// ============================================================================
// WORTDATENBANK - Hochstapler
// 150 Wörter pro Kategorie, je 3 INDIREKTE Assoziationen.
// Prinzip: Die Assoziation hilft dem Imposter zu bluffen, verrät aber NICHT
// das Thema. Beispiel: Pizza → "Freitagabend", nicht "Italien".
// ============================================================================

export type WordEntry = {
  word: string;
  associations: string[];
  category: string;
};

export type Category = string;

export type WordPack = Record<Category, [string, string[]][]>;

export const WORD_PACKS: WordPack = {

  // ==========================================================================
  'Essen & Trinken': [
    ['Pizza', ['Freitagabend', 'Karton', 'Lieferung']],
    ['Sushi', ['Stäbchen', 'Teller', 'Sojasoße']],
    ['Spaghetti', ['Gabel', 'drehen', 'Kleckerei']],
    ['Lasagne', ['Schichten', 'Auflaufform', 'Sonntag']],
    ['Tiramisu', ['Löffel', 'Dessert', 'Kaffeearoma']],
    ['Burger', ['beidhändig', 'Serviette', 'Imbiss']],
    ['Pommes', ['Tüte', 'Ketchup', 'Kino']],
    ['Döner', ['Mittagspause', 'Alufolie', 'Schlange']],
    ['Schnitzel', ['Sonntagsessen', 'Teller', 'Zitronenscheibe']],
    ['Gulasch', ['Topf', 'Winter', 'Oma']],
    ['Risotto', ['rühren', 'Geduld', 'cremig']],
    ['Paella', ['Pfanne', 'Urlaub', 'gelb']],
    ['Ramen', ['dampfend', 'Schüssel', 'Schlürfen']],
    ['Tacos', ['Hände', 'scharf', 'bunt']],
    ['Burrito', ['gerollt', 'Folie', 'gefüllt']],
    ['Hummus', ['dippen', 'cremig', 'Vorspeise']],
    ['Falafel', ['Kugel', 'knusprig', 'Pita']],
    ['Kebab', ['Grill', 'drehend', 'Spieß']],
    ['Croissant', ['Frühstück', 'krümelig', 'Café']],
    ['Baguette', ['unter Arm', 'Markt', 'Kruste']],
    ['Brezel', ['Oktoberfest', 'verknotet', 'grob']],
    ['Donut', ['rund', 'Glasur', 'Polizist']],
    ['Bagel', ['aufschneiden', 'Frühstück', 'Loch']],
    ['Pfannkuchen', ['Sonntag', 'wenden', 'stapeln']],
    ['Waffel', ['Jahrmarkt', 'Muster', 'Puderzucker']],
    ['Crêpe', ['dünn', 'Stand', 'faltbar']],
    ['Omelett', ['Frühstück', 'Pfanne', 'Füllung']],
    ['Rührei', ['Morgen', 'schaumig', 'Toast']],
    ['Käsekuchen', ['Blech', 'Oma', 'Kaffeetafel']],
    ['Apfelstrudel', ['Wien', 'Rosinen', 'dünn']],
    ['Schwarzwälder Kirschtorte', ['Geburtstag', 'Schnaps', 'Sahne']],
    ['Lebkuchen', ['Advent', 'Gewürze', 'hart']],
    ['Stollen', ['Weihnachten', 'Puderzucker', 'schwer']],
    ['Marzipan', ['formbar', 'Mandeln', 'Weihnachten']],
    ['Pralinen', ['Schachtel', 'Geschenk', 'Muttertag']],
    ['Baklava', ['klebrig', 'Nüsse', 'Sirup']],
    ['Churros', ['Spanien', 'Schokodip', 'frittiert']],
    ['Macaron', ['Paris', 'bunt', 'klein']],
    ['Panna Cotta', ['wackelig', 'Dessert', 'Beeren']],
    ['Crème Brûlée', ['knacken', 'karamellisiert', 'Löffel']],
    ['Mousse au Chocolat', ['luftig', 'Schälchen', 'Löffel']],
    ['Pudding', ['Kindheit', 'wackelig', 'Vanille']],
    ['Milchreis', ['Zimt', 'warm', 'Nachspeise']],
    ['Müsli', ['Schüssel', 'Frühstück', 'crunchy']],
    ['Joghurt', ['Becher', 'löffeln', 'Obst']],
    ['Quark', ['Frühstück', 'weiß', 'cremig']],
    ['Gouda', ['Scheibe', 'Frühstück', 'gelb']],
    ['Camembert', ['weich', 'Rinde', 'Frankreich']],
    ['Mozzarella', ['Kugel', 'Caprese', 'Büffel']],
    ['Parmesan', ['reiben', 'hart', 'Italien']],
    ['Feta', ['Salat', 'Griechenland', 'salzig']],
    ['Ricotta', ['mild', 'Füllung', 'Ravioli']],
    ['Blauschimmel', ['kräftig', 'Adern', 'Edel']],
    ['Tofu', ['Würfel', 'vegan', 'marinieren']],
    ['Lachs', ['rosa', 'geräuchert', 'Norwegen']],
    ['Thunfisch', ['Dose', 'Salat', 'Mittelmeer']],
    ['Forelle', ['Bach', 'Angeln', 'Pfanne']],
    ['Garnelen', ['pulen', 'rosa', 'Cocktail']],
    ['Hummer', ['Zange', 'teuer', 'Schere']],
    ['Muscheln', ['Topf', 'Strand', 'Weißwein']],
    ['Austern', ['Luxus', 'schlürfen', 'Meer']],
    ['Tintenfisch', ['Ringe', 'frittiert', 'Mittelmeer']],
    ['Kaviar', ['Luxus', 'Perlen', 'Löffelchen']],
    ['Hähnchen', ['Grill', 'Sonntag', 'knusprig']],
    ['Ente', ['Braten', 'knusprig', 'China']],
    ['Gans', ['Weihnachten', 'Braten', 'Rotkohl']],
    ['Pute', ['Thanksgiving', 'Braten', 'Familie']],
    ['Rind', ['Steak', 'rot', 'Grill']],
    ['Lamm', ['Ostern', 'zart', 'Kräuter']],
    ['Schwein', ['Braten', 'Kruste', 'Sonntag']],
    ['Speck', ['knusprig', 'Frühstück', 'Streifen']],
    ['Salami', ['Scheibe', 'Brot', 'würzig']],
    ['Schinken', ['Scheibe', 'Brötchen', 'geräuchert']],
    ['Bratwurst', ['Grill', 'Senf', 'Jahrmarkt']],
    ['Currywurst', ['Imbiss', 'Pappschale', 'Berlin']],
    ['Leberwurst', ['streichen', 'Brot', 'deftig']],
    ['Wiener', ['Paar', 'heiß', 'Kindheit']],
    ['Frikadelle', ['flach', 'rund', 'Brötchen']],
    ['Rouladen', ['gerollt', 'Sonntag', 'Soße']],
    ['Sauerbraten', ['Essig', 'Rheinland', 'dunkel']],
    ['Eisbein', ['deftig', 'Sauerkraut', 'Berlin']],
    ['Haxe', ['Biergarten', 'Bayern', 'Kruste']],
    ['Leberkäse', ['Semmel', 'Bayern', 'Scheibe']],
    ['Kartoffel', ['Erde', 'Beilage', 'stampfen']],
    ['Kartoffelbrei', ['cremig', 'Stampfer', 'Beilage']],
    ['Kartoffelsalat', ['Grillfest', 'Mayo', 'Schüssel']],
    ['Spätzle', ['Schwaben', 'Ei', 'Beilage']],
    ['Knödel', ['Kugel', 'Bayern', 'Soße']],
    ['Klöße', ['rund', 'Thüringen', 'Sonntag']],
    ['Reis', ['Beilage', 'Körner', 'Asien']],
    ['Couscous', ['Grieß', 'Orient', 'locker']],
    ['Bulgur', ['Salat', 'Orient', 'Körner']],
    ['Quinoa', ['gesund', 'Körner', 'Trend']],
    ['Linsen', ['Eintopf', 'rot', 'Indien']],
    ['Bohnen', ['Eintopf', 'grün', 'Dose']],
    ['Erbsen', ['rund', 'grün', 'Schote']],
    ['Kichererbsen', ['Dose', 'Orient', 'beige']],
    ['Sauerkraut', ['Fass', 'sauer', 'Würstchen']],
    ['Rotkohl', ['Weihnachten', 'süß-sauer', 'lila']],
    ['Spinat', ['grün', 'Popeye', 'Beilage']],
    ['Brokkoli', ['grün', 'Bäumchen', 'gesund']],
    ['Blumenkohl', ['weiß', 'Röschen', 'Gratin']],
    ['Rosenkohl', ['klein', 'Winter', 'bitter']],
    ['Möhre', ['orange', 'Hase', 'knackig']],
    ['Tomate', ['rot', 'Sommer', 'Salat']],
    ['Gurke', ['grün', 'Salat', 'Scheibe']],
    ['Paprika', ['bunt', 'Salat', 'süß']],
    ['Zucchini', ['länglich', 'grün', 'Pfanne']],
    ['Aubergine', ['lila', 'Mittelmeer', 'Moussaka']],
    ['Kürbis', ['Halloween', 'orange', 'Suppe']],
    ['Pilze', ['Wald', 'Pfanne', 'sammeln']],
    ['Champignons', ['weiß', 'Supermarkt', 'Pfanne']],
    ['Pfifferlinge', ['gelb', 'Wald', 'edel']],
    ['Steinpilze', ['edel', 'Wald', 'Risotto']],
    ['Apfel', ['rot', 'Baum', 'Schule']],
    ['Banane', ['gelb', 'schälen', 'Affe']],
    ['Birne', ['Baum', 'Obst', 'süß']],
    ['Erdbeere', ['rot', 'Sommer', 'Feld']],
    ['Himbeere', ['Strauch', 'rot', 'klein']],
    ['Heidelbeere', ['blau', 'Wald', 'Muffin']],
    ['Kirsche', ['Paar', 'Kern', 'Sommer']],
    ['Pflaume', ['Kern', 'blau', 'Kuchen']],
    ['Weintrauben', ['Rispe', 'Herbst', 'Lese']],
    ['Orange', ['Saft', 'schälen', 'Winter']],
    ['Zitrone', ['sauer', 'Scheibe', 'gelb']],
    ['Mango', ['exotisch', 'Kern', 'Urlaub']],
    ['Ananas', ['Krone', 'exotisch', 'Dose']],
    ['Kokosnuss', ['Schale', 'Palme', 'Strand']],
    ['Avocado', ['cremig', 'Toast', 'Brunch']],
    ['Oliven', ['Schale', 'Mittelmeer', 'Martini']],
    ['Nüsse', ['Schale', 'knacken', 'Weihnachten']],
    ['Mandeln', ['Weihnachten', 'gebrannt', 'Marzipan']],
    ['Haselnüsse', ['Nougat', 'Eichhörnchen', 'braun']],
    ['Walnüsse', ['Schale', 'Herbst', 'Hirn-Form']],
    ['Bier', ['Krug', 'Oktoberfest', 'Schaum']],
    ['Wein', ['Keller', 'schwenken', 'Dinner']],
    ['Sekt', ['Anstoßen', 'Silvester', 'Bläschen']],
    ['Champagner', ['Korken', 'Luxus', 'Bläschen']],
    ['Whisky', ['Glas', 'braun', 'Schottland']],
    ['Gin', ['Tonic', 'Wacholder', 'Bar']],
    ['Wodka', ['klar', 'Russland', 'Shot']],
    ['Rum', ['Karibik', 'Pirat', 'braun']],
    ['Tequila', ['Shot', 'Salz', 'Mexiko']],
    ['Cocktail', ['Bar', 'Schirmchen', 'bunt']],
    ['Mojito', ['Minze', 'Limette', 'Kuba']],
    ['Aperol Spritz', ['orange', 'Terrasse', 'Sommer']],
    ['Caipirinha', ['Limette', 'crushed ice', 'Brasilien']],
    ['Kaffee', ['Morgen', 'Tasse', 'aufwachen']],
    ['Espresso', ['klein', 'stark', 'Italien']],
    ['Cappuccino', ['Schaum', 'Herzchen', 'Frühstück']],
    ['Tee', ['Teekanne', 'Ruhe', 'heiß']],
    ['Kakao', ['Winter', 'Marshmallow', 'Kindheit']],
    ['Limonade', ['Sommer', 'Strohhalm', 'süß']],
  ],

  // ==========================================================================
  'Sport': [
    ['Fußball', ['Trikot', 'Stadion', 'Wochenende']],
    ['Basketball', ['Korb', 'Turnschuhe', 'Halle']],
    ['Handball', ['Halle', 'Wurf', 'Verein']],
    ['Volleyball', ['Netz', 'Strand', 'Team']],
    ['Tennis', ['Schläger', 'weiß', 'Ferien']],
    ['Padel', ['Glas', 'Doppel', 'Trend']],
    ['Tischtennis', ['Keller', 'schnell', 'Ping']],
    ['Badminton', ['Feder', 'Netz', 'Garten']],
    ['Squash', ['Wand', 'Halle', 'schnell']],
    ['Boxen', ['Handschuhe', 'Ring', 'Training']],
    ['Kickboxen', ['Matte', 'Schutz', 'Knie']],
    ['Karate', ['Gürtel', 'weiß', 'Disziplin']],
    ['Judo', ['Matte', 'Wurf', 'Gürtel']],
    ['Taekwondo', ['Tritt', 'Korea', 'Anzug']],
    ['Ringen', ['Matte', 'Olympia', 'griff']],
    ['MMA', ['Käfig', 'Mix', 'brutal']],
    ['Fechten', ['Maske', 'Klinge', 'elegant']],
    ['Bogenschießen', ['Ziel', 'Pfeil', 'Konzentration']],
    ['Schwimmen', ['Halle', 'Chlor', 'Bahn']],
    ['Wasserball', ['Becken', 'Team', 'Kappe']],
    ['Synchronschwimmen', ['Choreografie', 'Nase', 'Musik']],
    ['Wasserspringen', ['Brett', 'Anlauf', 'Saltos']],
    ['Surfen', ['Welle', 'Brett', 'Hawaii']],
    ['Kitesurfen', ['Wind', 'Strand', 'Schirm']],
    ['Windsurfen', ['Segel', 'Brett', 'Wind']],
    ['Stand Up Paddling', ['See', 'Gleichgewicht', 'Paddel']],
    ['Rudern', ['Boot', 'Fluss', 'Team']],
    ['Kanufahren', ['Paddel', 'See', 'Natur']],
    ['Kajak', ['eng', 'Fluss', 'Paddel']],
    ['Segeln', ['Wind', 'Küste', 'Leinen']],
    ['Skifahren', ['Berge', 'Winter', 'Hütte']],
    ['Snowboard', ['Berg', 'Park', 'cool']],
    ['Langlauf', ['Loipe', 'Winter', 'Ausdauer']],
    ['Skispringen', ['Schanze', 'Wind', 'weit']],
    ['Biathlon', ['Gewehr', 'Langlauf', 'Ziel']],
    ['Bobfahren', ['Eiskanal', 'Team', 'schnell']],
    ['Rodeln', ['Schlitten', 'Kindheit', 'Berg']],
    ['Eislaufen', ['Bahn', 'Kufen', 'Winter']],
    ['Eishockey', ['Puck', 'Halle', 'Kanada']],
    ['Eiskunstlauf', ['Choreografie', 'Musik', 'Sprung']],
    ['Curling', ['Stein', 'Besen', 'Eis']],
    ['Laufen', ['Schuhe', 'Park', 'Schweiß']],
    ['Joggen', ['Morgen', 'Playlist', 'Runde']],
    ['Marathon', ['42', 'Ausdauer', 'Menge']],
    ['Sprint', ['Startblock', 'Schnell', 'Sekunden']],
    ['Hürdenlauf', ['Balken', 'Rhythmus', 'Bahn']],
    ['Hochsprung', ['Matte', 'Latte', 'Fosbury']],
    ['Weitsprung', ['Anlauf', 'Sand', 'Balken']],
    ['Stabhochsprung', ['Stab', 'Höhe', 'Matte']],
    ['Kugelstoßen', ['Kreis', 'schwer', 'Wurf']],
    ['Diskuswerfen', ['drehen', 'Scheibe', 'Wurf']],
    ['Speerwerfen', ['Anlauf', 'Wurf', 'Bahn']],
    ['Hammerwerfen', ['drehen', 'Kreis', 'Wurf']],
    ['Triathlon', ['drei', 'Ausdauer', 'Wechsel']],
    ['Radfahren', ['Sattel', 'Helm', 'Route']],
    ['Mountainbike', ['Wald', 'Helm', 'Trail']],
    ['Rennrad', ['schmal', 'Kleidung', 'Tour']],
    ['BMX', ['Park', 'Tricks', 'klein']],
    ['Bahnradfahren', ['Oval', 'Halle', 'steil']],
    ['Klettern', ['Fels', 'Seil', 'Magnesium']],
    ['Bouldern', ['Halle', 'Matte', 'Route']],
    ['Bergsteigen', ['Gipfel', 'Ausrüstung', 'Alpen']],
    ['Wandern', ['Rucksack', 'Stiefel', 'Hütte']],
    ['Yoga', ['Matte', 'Atem', 'Namaste']],
    ['Pilates', ['Matte', 'Core', 'Kurs']],
    ['Crossfit', ['Box', 'Hantel', 'schwitzen']],
    ['Bodybuilding', ['Muskeln', 'Spiegel', 'Protein']],
    ['Gewichtheben', ['Hantel', 'Brust', 'Schrei']],
    ['Rudergerät', ['Studio', 'ziehen', 'Sitz']],
    ['Laufband', ['Studio', 'drinnen', 'Steigung']],
    ['Spinning', ['Studio', 'Musik', 'schwitzen']],
    ['Zumba', ['Musik', 'tanzen', 'Kurs']],
    ['Aerobic', ['80er', 'Stirnband', 'Kurs']],
    ['Golf', ['Rasen', 'Caddy', 'Loch']],
    ['Minigolf', ['Familie', 'Hindernis', 'Urlaub']],
    ['Bowling', ['Schuhe', 'Bahn', 'Feierabend']],
    ['Billard', ['grün', 'Queue', 'Kugel']],
    ['Dart', ['Kneipe', 'Ziel', 'Wurf']],
    ['Kegeln', ['Verein', 'Bahn', 'Stammtisch']],
    ['Reiten', ['Pferd', 'Halle', 'Helm']],
    ['Polo', ['Pferd', 'elegant', 'Schläger']],
    ['Hindernisreiten', ['Pferd', 'Sprung', 'Turnier']],
    ['Dressur', ['Pferd', 'elegant', 'Choreografie']],
    ['Turnen', ['Reck', 'Halle', 'Matte']],
    ['Bodenturnen', ['Matte', 'Salto', 'Musik']],
    ['Stufenbarren', ['Turnen', 'Hände', 'schwingen']],
    ['Schwebebalken', ['Turnen', 'Gleichgewicht', 'schmal']],
    ['Rhythmische Sportgymnastik', ['Band', 'Reifen', 'Musik']],
    ['Trampolin', ['Sprung', 'Garten', 'Kindheit']],
    ['Parkour', ['Stadt', 'springen', 'Hindernis']],
    ['Skateboard', ['Brett', 'Rampe', 'Park']],
    ['Inlineskating', ['Rollen', 'Asphalt', 'Helm']],
    ['Rollerskating', ['Retro', 'Rollschuh', 'Disco']],
    ['Motorsport', ['Rennen', 'Lärm', 'Helm']],
    ['Formel 1', ['Rennen', 'Helm', 'TV']],
    ['Rallye', ['Schotter', 'Beifahrer', 'Wald']],
    ['MotoGP', ['Kurve', 'Knie', 'Helm']],
    ['Motocross', ['Schlamm', 'Sprung', 'Helm']],
    ['NASCAR', ['USA', 'Oval', 'laut']],
    ['Segway', ['stehend', 'Touri', 'Stadt']],
    ['Cheerleading', ['Pompom', 'Wurf', 'USA']],
    ['Tanzen', ['Paar', 'Musik', 'Saal']],
    ['Standardtanz', ['Frack', 'Turnier', 'Paar']],
    ['Breakdance', ['Boden', 'Kreis', 'Olympia']],
    ['Ballett', ['Spitzen', 'Tutu', 'Bühne']],
    ['Flamenco', ['Kastagnetten', 'Spanien', 'rot']],
    ['Salsa', ['Paar', 'Musik', 'Kuba']],
    ['Tango', ['Paar', 'ernst', 'Argentinien']],
    ['Hip-Hop', ['Baggy', 'Crew', 'urban']],
    ['Schach', ['König', 'denken', 'Uhr']],
    ['Poker', ['Karten', 'Chips', 'Las Vegas']],
    ['Rugby', ['Ei', 'hart', 'England']],
    ['American Football', ['Helm', 'Superbowl', 'TV']],
    ['Baseball', ['Schläger', 'Basen', 'USA']],
    ['Softball', ['Basen', 'weiblich', 'Wiese']],
    ['Cricket', ['England', 'weiß', 'lang']],
    ['Lacrosse', ['Netz', 'Stock', 'USA']],
    ['Floorball', ['Halle', 'Stock', 'Plastik']],
    ['Wasserski', ['Boot', 'Leine', 'See']],
    ['Wakeboard', ['Boot', 'Brett', 'See']],
    ['Tauchen', ['Flasche', 'Tiefe', 'Riff']],
    ['Schnorcheln', ['Maske', 'Oberfläche', 'Urlaub']],
    ['Drachenfliegen', ['Wind', 'Berg', 'Gurt']],
    ['Paragliding', ['Schirm', 'Berg', 'Sprung']],
    ['Fallschirmspringen', ['Flugzeug', 'Schirm', 'Adrenalin']],
    ['Bungeejumping', ['Seil', 'Brücke', 'Adrenalin']],
    ['Airhockey', ['Tisch', 'Luft', 'Arcade']],
    ['Capoeira', ['Brasilien', 'Musik', 'Kreis']],
    ['Sumo', ['Japan', 'Kreis', 'groß']],
    ['Hindernislauf', ['Schlamm', 'Team', 'hart']],
    ['Schießsport', ['Ziel', 'Konzentration', 'Olympia']],
    ['Angeln', ['See', 'Geduld', 'Rute']],
    ['Jagd', ['Wald', 'Morgen', 'grün']],
    ['Reitsport', ['Stall', 'Pferd', 'Turnier']],
    ['Petanque', ['Kugel', 'Frankreich', 'Park']],
    ['Boule', ['Kugel', 'Park', 'Frankreich']],
    ['Frisbee', ['Wiese', 'Scheibe', 'Hund']],
    ['Ultimate', ['Scheibe', 'Team', 'Wiese']],
    ['Tauziehen', ['Team', 'Seil', 'Kirmes']],
    ['Sackhüpfen', ['Kindheit', 'Fest', 'Wiese']],
    ['Eierlaufen', ['Löffel', 'Kindergeburtstag', 'Balance']],
    ['Dodgeball', ['Ball', 'werfen', 'Schulhof']],
    ['Völkerball', ['Schulhof', 'Team', 'werfen']],
  ],

  // ==========================================================================
  'Filme & Serien': [
    ['Star Wars', ['Weltraum', 'Laserschwert', 'Kult']],
    ['Star Trek', ['Raumschiff', 'beamen', 'Science']],
    ['Harry Potter', ['Zauber', 'Schule', 'Buch']],
    ['Herr der Ringe', ['Neuseeland', 'episch', 'lang']],
    ['Der Hobbit', ['Reise', 'klein', 'Buch']],
    ['Game of Thrones', ['Thron', 'Drachen', 'Schock']],
    ['House of the Dragon', ['Prequel', 'Familie', 'Drachen']],
    ['Breaking Bad', ['Wüste', 'blau', 'Lehrer']],
    ['Better Call Saul', ['Anwalt', 'grau', 'Prequel']],
    ['The Walking Dead', ['Untergang', 'Gruppe', 'Überleben']],
    ['Stranger Things', ['Kinder', 'Fahrrad', '80er']],
    ['Dark', ['deutsch', 'Zeit', 'Höhle']],
    ['Squid Game', ['grün', 'Korea', 'Spiele']],
    ['Money Heist', ['Maske', 'Spanien', 'rot']],
    ['Narcos', ['Kolumbien', 'Drogen', 'Netflix']],
    ['The Crown', ['England', 'Royals', 'Geschichte']],
    ['Friends', ['Couch', 'New York', 'Kaffee']],
    ['How I Met Your Mother', ['Bar', 'Freunde', 'lange']],
    ['The Big Bang Theory', ['Nerds', 'Comic', 'Lachen']],
    ['Seinfeld', ['90er', 'New York', 'nichts']],
    ['The Office', ['Büro', 'Mockumentary', 'Papier']],
    ['Parks and Recreation', ['Stadtrat', 'Waffeln', 'Kleinstadt']],
    ['Brooklyn Nine-Nine', ['Polizei', 'Comedy', 'Halloween']],
    ['Modern Family', ['Familie', 'Mockumentary', 'chaotisch']],
    ['The Simpsons', ['gelb', 'lang', 'Donut']],
    ['Family Guy', ['Baby', 'Hund', 'derb']],
    ['South Park', ['Berge', 'Colorado', 'derb']],
    ['Rick and Morty', ['Portal', 'Universen', 'Wissenschaft']],
    ['Bojack Horseman', ['Pferd', 'Hollywood', 'traurig']],
    ['The Last of Us', ['Pilz', 'Reise', 'Spiel']],
    ['The Mandalorian', ['Helm', 'Wüste', 'Baby']],
    ['The Witcher', ['Schwert', 'weiß', 'Buch']],
    ['Peaky Blinders', ['Mütze', 'Birmingham', 'Familie']],
    ['Vikings', ['Nordmänner', 'Schiff', 'Axt']],
    ['Rome', ['Antike', 'Sandalen', 'HBO']],
    ['Sex and the City', ['New York', 'Schuhe', 'vier']],
    ['Desperate Housewives', ['Vorort', 'Geheimnisse', 'rosa']],
    ['Grey\'s Anatomy', ['Krankenhaus', 'Drama', 'Ärzte']],
    ['House M.D.', ['Stock', 'Diagnose', 'grumpy']],
    ['Dr. House', ['Stock', 'Diagnose', 'sarkastisch']],
    ['Lost', ['Insel', 'Flugzeug', 'Fragen']],
    ['The X-Files', ['Akten', 'Alien', 'FBI']],
    ['Twin Peaks', ['Kirsche', 'Kaffee', 'bizarr']],
    ['True Detective', ['Partner', 'düster', 'Süden']],
    ['Mindhunter', ['FBI', 'Interview', 'Profil']],
    ['Sherlock', ['Lupe', 'London', 'clever']],
    ['Black Mirror', ['dystopisch', 'Episoden', 'Technik']],
    ['Westworld', ['Park', 'Androiden', 'Western']],
    ['The Handmaid\'s Tale', ['rot', 'dystopisch', 'Buch']],
    ['The Boys', ['anti', 'blutig', 'Superhelden']],
    ['The Umbrella Academy', ['Geschwister', 'Familie', 'Netflix']],
    ['Daredevil', ['blind', 'rot', 'Anwalt']],
    ['Wednesday', ['schwarz', 'Schule', 'Tanz']],
    ['Euphoria', ['Teenager', 'Glitzer', 'Drogen']],
    ['The White Lotus', ['Hotel', 'reich', 'Urlaub']],
    ['Succession', ['Familie', 'Firma', 'Erben']],
    ['Yellowstone', ['Ranch', 'Montana', 'Familie']],
    ['Ozark', ['Wasser', 'Geldwäsche', 'See']],
    ['House of Cards', ['Politik', 'Washington', 'Kamera']],
    ['The West Wing', ['Politik', 'Washington', 'schnell']],
    ['Veep', ['Politik', 'Komik', 'Flüche']],
    ['Mad Men', ['Werbung', '60er', 'Anzug']],
    ['The Sopranos', ['Mafia', 'New Jersey', 'Familie']],
    ['The Wire', ['Baltimore', 'Polizei', 'real']],
    ['Fargo', ['Schnee', 'Unfall', 'Minnesota']],
    ['Barry', ['Auftrag', 'Schauspiel', 'dunkel']],
    ['Atlanta', ['Rap', 'surreal', 'Süden']],
    ['Shameless', ['Familie', 'Chicago', 'arm']],
    ['Arrested Development', ['Familie', 'Bananenstand', 'Pleite']],
    ['It\'s Always Sunny', ['Bar', 'Philadelphia', 'schräg']],
    ['Curb Your Enthusiasm', ['Larry', 'peinlich', 'LA']],
    ['Entourage', ['Hollywood', 'Jungs', 'HBO']],
    ['Ted Lasso', ['Trainer', 'Football', 'Schnurrbart']],
    ['Shrinking', ['Therapie', 'Freunde', 'Trauer']],
    ['Severance', ['Büro', 'Trennung', 'Apple']],
    ['Silo', ['Turm', 'dystopisch', 'Buch']],
    ['Foundation', ['Galaxie', 'Asimov', 'Imperium']],
    ['Titanic', ['Schiff', 'Eisberg', 'Liebe']],
    ['Avatar', ['blau', 'Pandora', 'CGI']],
    ['Jurassic Park', ['Insel', 'Gehege', 'Jeep']],
    ['Indiana Jones', ['Hut', 'Peitsche', 'Archäologie']],
    ['James Bond', ['Martini', 'Anzug', '007']],
    ['Mission Impossible', ['Tom', 'Stunts', 'Maske']],
    ['Fast and Furious', ['Autos', 'Familie', 'Nitro']],
    ['Matrix', ['Pille', 'grün', 'Code']],
    ['Inception', ['Traum', 'Schichten', 'Kreisel']],
    ['Interstellar', ['All', 'Zeit', 'Bücherregal']],
    ['Oppenheimer', ['Bombe', 'schwarzweiß', 'Physik']],
    ['Barbie', ['rosa', 'Plastik', 'Spielzeug']],
    ['Forrest Gump', ['Bank', 'Laufen', 'Schokolade']],
    ['Pulp Fiction', ['Koffer', 'Tanz', 'Tarantino']],
    ['Fight Club', ['Seife', 'Regeln', 'Twist']],
    ['The Godfather', ['Mafia', 'Pate', 'Orange']],
    ['Schindler\'s List', ['schwarzweiß', 'Liste', 'rot']],
    ['The Dark Knight', ['Maske', 'Gotham', 'Chaos']],
    ['Avengers', ['Team', 'Helden', 'Marvel']],
    ['Iron Man', ['Anzug', 'Tony', 'Marvel']],
    ['Spider-Man', ['Netz', 'New York', 'Marvel']],
    ['Batman', ['Höhle', 'Gotham', 'Fledermaus']],
    ['Superman', ['Umhang', 'Telefonzelle', 'DC']],
    ['Wonder Woman', ['Lasso', 'Amazone', 'DC']],
    ['Joker', ['Lächeln', 'Farbe', 'Treppe']],
    ['Deadpool', ['rot', 'Kamera', 'Witze']],
    ['Frozen', ['Eis', 'Schwestern', 'Lied']],
    ['The Lion King', ['Afrika', 'König', 'Vater']],
    ['Toy Story', ['Spielzeug', 'Cowboy', 'Pixar']],
    ['Finding Nemo', ['Meer', 'Fisch', 'orange']],
    ['Shrek', ['grün', 'Sumpf', 'Oger']],
    ['Ice Age', ['Eis', 'Eichhörnchen', 'Gruppe']],
    ['Madagascar', ['Zoo', 'Tiere', 'Insel']],
    ['Kung Fu Panda', ['Panda', 'China', 'Nudeln']],
    ['Ratatouille', ['Ratte', 'Paris', 'Küche']],
    ['WALL-E', ['Roboter', 'Erde', 'Müll']],
    ['Up', ['Ballons', 'Haus', 'alt']],
    ['Inside Out', ['Gefühle', 'Kopf', 'bunt']],
    ['Coco', ['Tote', 'Gitarre', 'Mexiko']],
    ['Fluch der Karibik', ['Piraten', 'Schiff', 'Kompass']],
    ['Der Pate', ['Mafia', 'orange', 'Familie']],
    ['Scarface', ['Miami', 'Kokain', 'Hallo']],
    ['Goodfellas', ['Mafia', 'New York', 'Scorsese']],
    ['Casino', ['Vegas', 'Mafia', 'Scorsese']],
    ['Heat', ['Raub', 'LA', 'Profi']],
    ['Se7en', ['Sünden', 'Regen', 'Box']],
    ['The Silence of the Lambs', ['Maske', 'FBI', 'Schmetterling']],
    ['American Beauty', ['Rose', 'Vorort', 'Krise']],
    ['The Shawshank Redemption', ['Gefängnis', 'Tunnel', 'Freundschaft']],
    ['Green Mile', ['Gefängnis', 'Maus', 'Wunder']],
    ['Rocky', ['Treppe', 'Philadelphia', 'Boxer']],
    ['Gladiator', ['Rom', 'Arena', 'Rache']],
    ['Braveheart', ['Schottland', 'blau', 'Freiheit']],
    ['Pretty Woman', ['Hollywood', 'Shopping', 'rot']],
    ['Notting Hill', ['London', 'Buchladen', 'Liebe']],
    ['Die Hard', ['Hochhaus', 'Weihnachten', 'Barfuß']],
    ['Terminator', ['Maschine', 'Zukunft', 'Brille']],
    ['Alien', ['All', 'Säure', 'dunkel']],
    ['Predator', ['Dschungel', 'unsichtbar', 'Maske']],
    ['Rambo', ['Dschungel', 'Messer', 'Stirnband']],
    ['Top Gun', ['Jet', 'Sonnenbrille', 'Kadett']],
    ['Ghostbusters', ['Proton', 'grün', 'New York']],
    ['Back to the Future', ['DeLorean', 'Zeit', 'Blitz']],
    ['E.T.', ['Fahrrad', 'Mond', 'Zuhause']],
    ['Gremlins', ['Wasser', 'Nacht', 'klein']],
    ['Jumanji', ['Spiel', 'Dschungel', 'Trommeln']],
    ['The Mask', ['grün', 'Cartoon', 'Carrey']],
    ['Ace Ventura', ['Haare', 'Tiere', 'Carrey']],
    ['Dumb and Dumber', ['Bob', 'Van', 'Carrey']],
    ['Der Schuh des Manitu', ['Winnetou', 'Bully', 'Parodie']],
    ['Keinohrhasen', ['Til', 'Romantik', 'deutsch']],
    ['Good Bye Lenin', ['Mauer', 'DDR', 'Mutter']],
    ['Das Leben der Anderen', ['Stasi', 'Wanze', 'DDR']],
    ['Lola rennt', ['rot', 'Berlin', 'Tempo']],
    ['Tatort', ['Sonntag', 'Ermittler', 'ARD']],
    ['Polizeiruf', ['Sonntag', 'Osten', 'ARD']],
    ['Jujutsu Kaisen', ['Fluch', 'Anime', 'Finger']],
    ['Demon Slayer', ['Schwert', 'Atmung', 'Anime']],
  ],
  // ==========================================================================
  'Berufe': [
    ['Arzt', ['Praxis', 'Kittel', 'Rezept']],
    ['Chirurg', ['Maske', 'Skalpell', 'Team']],
    ['Zahnarzt', ['Stuhl', 'Bohrer', 'Angst']],
    ['Kinderarzt', ['Wartezimmer', 'Spielzeug', 'Impfung']],
    ['Tierarzt', ['Praxis', 'Tiere', 'Tabletten']],
    ['Krankenschwester', ['Schicht', 'Spritze', 'Station']],
    ['Pfleger', ['Heim', 'Schicht', 'helfen']],
    ['Sanitäter', ['Blaulicht', 'Einsatz', 'schnell']],
    ['Hebamme', ['Geburt', 'Säugling', 'Hausbesuch']],
    ['Physiotherapeut', ['Praxis', 'Liege', 'Rücken']],
    ['Psychologe', ['Couch', 'zuhören', 'Gespräch']],
    ['Psychiater', ['Klinik', 'Medikament', 'Gespräch']],
    ['Apotheker', ['Schublade', 'weißer Kittel', 'Beratung']],
    ['Optiker', ['Brille', 'Gestell', 'Sehtest']],
    ['Orthopäde', ['Knochen', 'Röntgen', 'Praxis']],
    ['Lehrer', ['Tafel', 'Pause', 'Klasse']],
    ['Grundschullehrer', ['ABC', 'klein', 'Kreide']],
    ['Professor', ['Vorlesung', 'Talar', 'Forschung']],
    ['Dozent', ['Hörsaal', 'Folien', 'Uni']],
    ['Erzieher', ['Kita', 'Kreis', 'singen']],
    ['Sozialarbeiter', ['Beratung', 'Akten', 'Amt']],
    ['Bibliothekar', ['Regal', 'still', 'Karte']],
    ['Pilot', ['Uniform', 'Cockpit', 'Kaffee']],
    ['Stewardess', ['Lächeln', 'Gang', 'Wagen']],
    ['Lokführer', ['Kabine', 'Schiene', 'Fahrplan']],
    ['Busfahrer', ['Linie', 'Ticket', 'Runde']],
    ['Taxifahrer', ['Kennzeichen', 'Meter', 'Nacht']],
    ['LKW-Fahrer', ['Autobahn', 'Pause', 'lang']],
    ['Kapitän', ['Mütze', 'Brücke', 'Wellen']],
    ['Matrose', ['Deck', 'Knoten', 'See']],
    ['Koch', ['Mütze', 'Hektik', 'Messer']],
    ['Konditor', ['Süß', 'Torte', 'Creme']],
    ['Bäcker', ['Morgen', 'Mehl', 'Ofen']],
    ['Metzger', ['Kittel', 'Beil', 'Theke']],
    ['Kellner', ['Tablett', 'Notizblock', 'Trinkgeld']],
    ['Barkeeper', ['Shaker', 'Nacht', 'Glas']],
    ['Sommelier', ['Wein', 'Keller', 'Nase']],
    ['Polizist', ['Uniform', 'Streife', 'Funkgerät']],
    ['Kommissar', ['Akten', 'Verhör', 'Revier']],
    ['Soldat', ['Uniform', 'Kaserne', 'Befehl']],
    ['Feuerwehrmann', ['Schlauch', 'Leiter', 'rot']],
    ['Rettungssanitäter', ['Blaulicht', 'Trage', 'Einsatz']],
    ['Wachmann', ['Tor', 'Kamera', 'Nacht']],
    ['Detektiv', ['Lupe', 'Schatten', 'Fall']],
    ['Anwalt', ['Robe', 'Akten', 'Mandant']],
    ['Richter', ['Hammer', 'Robe', 'Saal']],
    ['Staatsanwalt', ['Anklage', 'Akten', 'Gericht']],
    ['Notar', ['Siegel', 'Urkunde', 'Büro']],
    ['Steuerberater', ['Formular', 'Zahlen', 'Fristen']],
    ['Buchhalter', ['Zahlen', 'Tabelle', 'Bilanz']],
    ['Banker', ['Anzug', 'Frankfurt', 'Boni']],
    ['Börsenmakler', ['Bildschirme', 'Zahlen', 'Stress']],
    ['Versicherungsvertreter', ['Formular', 'Police', 'Hausbesuch']],
    ['Immobilienmakler', ['Schlüssel', 'Besichtigung', 'Provision']],
    ['Architekt', ['Zeichnung', 'Modell', 'Büro']],
    ['Bauingenieur', ['Plan', 'Helm', 'Baustelle']],
    ['Bauarbeiter', ['Helm', 'Gerüst', 'Baustelle']],
    ['Maurer', ['Ziegel', 'Kelle', 'Mörtel']],
    ['Zimmermann', ['Holz', 'Dach', 'Hammer']],
    ['Dachdecker', ['oben', 'Ziegel', 'Leiter']],
    ['Elektriker', ['Kabel', 'Schrauben', 'Sicherung']],
    ['Installateur', ['Rohr', 'Werkzeug', 'Bad']],
    ['Maler', ['Pinsel', 'Leiter', 'Abdeckplane']],
    ['Fliesenleger', ['Fuge', 'Bad', 'Knie']],
    ['Schreiner', ['Hobel', 'Holz', 'Werkstatt']],
    ['Tischler', ['Holz', 'Möbel', 'Werkstatt']],
    ['Schlosser', ['Schlüssel', 'Metall', 'Werkstatt']],
    ['Schmied', ['Amboss', 'Feuer', 'Hammer']],
    ['Mechaniker', ['Öl', 'Werkzeug', 'Werkstatt']],
    ['Mechatroniker', ['Motor', 'Computer', 'Auto']],
    ['Schweißer', ['Maske', 'Funken', 'Metall']],
    ['Programmierer', ['Bildschirm', 'Code', 'Kaffee']],
    ['Informatiker', ['Bildschirm', 'Server', 'Logik']],
    ['Data Scientist', ['Zahlen', 'Modell', 'Python']],
    ['Webdesigner', ['Layout', 'Farben', 'Browser']],
    ['UX Designer', ['Nutzer', 'Prototyp', 'Figma']],
    ['Grafikdesigner', ['Logo', 'Farben', 'Mappe']],
    ['Fotograf', ['Objektiv', 'Stativ', 'Licht']],
    ['Kameramann', ['Filmset', 'Objektiv', 'Kabel']],
    ['Regisseur', ['Set', 'Stuhl', 'Action']],
    ['Drehbuchautor', ['Skript', 'Szene', 'Laptop']],
    ['Schauspieler', ['Bühne', 'Rolle', 'Probe']],
    ['Synchronsprecher', ['Studio', 'Mikrofon', 'Stimme']],
    ['Sänger', ['Mikrofon', 'Bühne', 'Fans']],
    ['Musiker', ['Instrument', 'Band', 'Gig']],
    ['Komponist', ['Noten', 'Klavier', 'Orchester']],
    ['Dirigent', ['Stab', 'Orchester', 'Frack']],
    ['Pianist', ['Tasten', 'Konzert', 'Übung']],
    ['Gitarrist', ['Saiten', 'Band', 'Plektrum']],
    ['Schlagzeuger', ['Stöcke', 'Takt', 'Band']],
    ['DJ', ['Platten', 'Club', 'Nacht']],
    ['Produzent', ['Studio', 'Beats', 'Mixer']],
    ['Autor', ['Manuskript', 'Kaffee', 'Deadline']],
    ['Journalist', ['Block', 'Interview', 'Deadline']],
    ['Reporter', ['Mikrofon', 'Live', 'Kamera']],
    ['Redakteur', ['Text', 'Büro', 'Abgabe']],
    ['Moderator', ['Studio', 'Ohrstöpsel', 'Live']],
    ['Influencer', ['Handy', 'Selfie', 'Kooperation']],
    ['Content Creator', ['Kamera', 'Edit', 'Plattform']],
    ['Youtuber', ['Kamera', 'Abo', 'Edit']],
    ['Blogger', ['Laptop', 'Café', 'Thema']],
    ['Podcaster', ['Mikrofon', 'Gast', 'Folge']],
    ['Modedesigner', ['Schnitt', 'Kollektion', 'Laufsteg']],
    ['Model', ['Laufsteg', 'Casting', 'Kamera']],
    ['Visagist', ['Pinsel', 'Palette', 'Gesicht']],
    ['Friseur', ['Schere', 'Spiegel', 'Föhn']],
    ['Barbier', ['Rasur', 'Pflege', 'Bart']],
    ['Kosmetikerin', ['Liege', 'Pflege', 'ruhig']],
    ['Nageldesignerin', ['Feile', 'Lack', 'Finger']],
    ['Schneider', ['Nadel', 'Maß', 'Werkstatt']],
    ['Schuster', ['Leder', 'Reparatur', 'Werkstatt']],
    ['Gärtner', ['Erde', 'Schaufel', 'Pflanze']],
    ['Landwirt', ['Traktor', 'Feld', 'Ernte']],
    ['Imker', ['Schleier', 'Wabe', 'Honig']],
    ['Förster', ['Wald', 'Jagd', 'grün']],
    ['Winzer', ['Reben', 'Keller', 'Fass']],
    ['Fischer', ['Netz', 'Boot', 'Morgen']],
    ['Bergmann', ['Helm', 'Tiefe', 'Lampe']],
    ['Müllmann', ['Tonne', 'Morgen', 'Wagen']],
    ['Reinigungskraft', ['Wischmopp', 'Eimer', 'abends']],
    ['Hausmeister', ['Schlüsselbund', 'Keller', 'Werkzeug']],
    ['Gebäudereiniger', ['Gerüst', 'Fenster', 'Höhe']],
    ['Paketbote', ['Uniform', 'Klingel', 'Wagen']],
    ['Postbote', ['gelb', 'Fahrrad', 'Tasche']],
    ['Kurier', ['Rad', 'schnell', 'Rucksack']],
    ['Verkäufer', ['Theke', 'Kasse', 'Beratung']],
    ['Kassierer', ['Scanner', 'Kasse', 'Schlange']],
    ['Florist', ['Strauß', 'Schere', 'Laden']],
    ['Juwelier', ['Vitrine', 'Ring', 'Lupe']],
    ['Antiquitätenhändler', ['alt', 'Laden', 'Schätzung']],
    ['Buchhändler', ['Regal', 'Empfehlung', 'Laden']],
    ['Galerist', ['Bilder', 'Ausstellung', 'Wein']],
    ['Kurator', ['Museum', 'Sammlung', 'Schilder']],
    ['Übersetzer', ['Sprachen', 'Text', 'Wörterbuch']],
    ['Dolmetscher', ['Kabine', 'Kopfhörer', 'live']],
    ['Diplomat', ['Botschaft', 'Anzug', 'Protokoll']],
    ['Politiker', ['Rede', 'Anzug', 'Bühne']],
    ['Bürgermeister', ['Rathaus', 'Schärpe', 'Stadt']],
    ['Pfarrer', ['Kanzel', 'Gemeinde', 'Talar']],
    ['Priester', ['Kirche', 'Messe', 'Gewand']],
    ['Rabbiner', ['Synagoge', 'Tora', 'Bart']],
    ['Imam', ['Moschee', 'Gebet', 'Freitag']],
    ['Mönch', ['Kloster', 'Kutte', 'still']],
    ['Astronaut', ['All', 'Helm', 'Training']],
    ['Kosmonaut', ['All', 'Russland', 'Station']],
    ['Wissenschaftler', ['Labor', 'Kittel', 'Forschung']],
    ['Biologe', ['Mikroskop', 'Feld', 'Probe']],
    ['Chemiker', ['Kolben', 'Labor', 'Formel']],
    ['Physiker', ['Formel', 'Tafel', 'Teilchen']],
    ['Mathematiker', ['Tafel', 'Beweis', 'Papier']],
    ['Statistiker', ['Tabelle', 'Zahl', 'Kurve']],
    ['Geologe', ['Stein', 'Hammer', 'Gelände']],
    ['Archäologe', ['Pinsel', 'Grabung', 'Fund']],
    ['Historiker', ['Archiv', 'Buch', 'Quelle']],
    ['Philosoph', ['denken', 'Buch', 'Debatte']],
    ['Trainer', ['Trillerpfeife', 'Plan', 'Team']],
    ['Fitnesstrainer', ['Studio', 'Plan', 'Muskeln']],
    ['Personal Trainer', ['eins zu eins', 'Studio', 'Plan']],
    ['Yogalehrer', ['Matte', 'Atmung', 'Kurs']],
    ['Tanzlehrer', ['Saal', 'Takt', 'Paar']],
    ['Reiseleiter', ['Gruppe', 'Fähnchen', 'Mikrofon']],
  ],

  // ==========================================================================
  'Alltag & Haushalt': [
    ['Staubsauger', ['Kabel', 'Laut', 'Sonntag']],
    ['Waschmaschine', ['Keller', 'Trommel', 'Programm']],
    ['Trockner', ['Wärme', 'Flusen', 'Bequemlichkeit']],
    ['Geschirrspüler', ['Tab', 'offen', 'nach dem Essen']],
    ['Kühlschrank', ['Magnet', 'leuchten', 'Tür']],
    ['Gefrierschrank', ['kalt', 'Vorrat', 'Eisblock']],
    ['Herd', ['Platte', 'heiß', 'Topf']],
    ['Backofen', ['Sonntag', 'Blech', 'warm']],
    ['Mikrowelle', ['Piepen', 'aufwärmen', 'Drehteller']],
    ['Wasserkocher', ['Pfeifen', 'Morgen', 'Kabel']],
    ['Toaster', ['Frühstück', 'Zeit', 'schwarz']],
    ['Kaffeemaschine', ['Gluckern', 'Morgen', 'Filter']],
    ['Espressomaschine', ['Hebel', 'Duft', 'Barista']],
    ['Mixer', ['Standfuß', 'Smoothie', 'laut']],
    ['Pürierstab', ['Hand', 'Suppe', 'schnell']],
    ['Küchenmaschine', ['Aufsätze', 'Teig', 'wuchtig']],
    ['Bügeleisen', ['Dampf', 'Hemd', 'heiß']],
    ['Nähmaschine', ['Faden', 'Nadel', 'Pedal']],
    ['Staubwedel', ['Regal', 'sanft', 'Feder']],
    ['Besen', ['kehren', 'Ecke', 'Holz']],
    ['Wischmopp', ['Eimer', 'Boden', 'nass']],
    ['Eimer', ['Wasser', 'Putzen', 'Henkel']],
    ['Schrubber', ['Bürste', 'Dreck', 'Garten']],
    ['Schwamm', ['Spüle', 'zwei Seiten', 'gelb']],
    ['Spüllappen', ['Küche', 'nass', 'Theke']],
    ['Geschirrtuch', ['hängen', 'trocknen', 'kariert']],
    ['Putzlappen', ['Staub', 'Regal', 'alt']],
    ['Mülltonne', ['Hof', 'Deckel', 'Woche']],
    ['Mülleimer', ['Küche', 'Beutel', 'Pedal']],
    ['Müllbeutel', ['Rolle', 'schwarz', 'tragen']],
    ['Gelber Sack', ['Plastik', 'Abholung', 'gelb']],
    ['Biomülltonne', ['grün', 'Reste', 'stinken']],
    ['Altglascontainer', ['klirren', 'Parkplatz', 'Sonntag']],
    ['Kompost', ['Garten', 'Erde', 'verrotten']],
    ['Gartenschlauch', ['Wasser', 'Trommel', 'Sommer']],
    ['Rasenmäher', ['Samstag', 'laut', 'Nachbar']],
    ['Rasenkante', ['trimmen', 'Rand', 'Garten']],
    ['Heckenschere', ['hoch', 'Nachbar', 'schneiden']],
    ['Gießkanne', ['Blumen', 'Wasser', 'Tülle']],
    ['Spaten', ['Beet', 'Erde', 'Garten']],
    ['Harke', ['Laub', 'Herbst', 'Garten']],
    ['Schaufel', ['Erde', 'Sandkasten', 'Loch']],
    ['Schneeschieber', ['Winter', 'Einfahrt', 'Morgen']],
    ['Leiter', ['Höhe', 'Keller', 'Balance']],
    ['Werkzeugkasten', ['Keller', 'klappern', 'Metall']],
    ['Hammer', ['Nagel', 'schlagen', 'Holz']],
    ['Schraubendreher', ['Kreuz', 'Schlitz', 'drehen']],
    ['Zange', ['greifen', 'Metall', 'Werkzeug']],
    ['Säge', ['Holz', 'hin-her', 'Staub']],
    ['Bohrmaschine', ['Wand', 'Dübel', 'laut']],
    ['Akkuschrauber', ['Akku', 'Schrauben', 'schnell']],
    ['Maßband', ['messen', 'ausziehen', 'Zahlen']],
    ['Wasserwaage', ['gerade', 'Blase', 'Wand']],
    ['Dübel', ['Wand', 'Bohrer', 'halten']],
    ['Nagel', ['Hammer', 'Wand', 'Bild']],
    ['Schraube', ['Dreher', 'drehen', 'halten']],
    ['Steckdose', ['Wand', 'Stecker', 'Strom']],
    ['Glühbirne', ['Fassung', 'Idee', 'Licht']],
    ['Lampe', ['Schirm', 'Ecke', 'Licht']],
    ['Deckenleuchte', ['oben', 'Zimmer', 'Schalter']],
    ['Stehlampe', ['Ecke', 'Wohnzimmer', 'hoch']],
    ['Nachttischlampe', ['lesen', 'Bett', 'warm']],
    ['Kerze', ['Docht', 'Wachs', 'Abend']],
    ['Teelicht', ['klein', 'Alu', 'romantisch']],
    ['Vase', ['Blumen', 'Tisch', 'Glas']],
    ['Bilderrahmen', ['Wand', 'Foto', 'Erinnerung']],
    ['Spiegel', ['Flur', 'Blick', 'Glas']],
    ['Uhr', ['Wand', 'ticken', 'Zeit']],
    ['Wecker', ['Morgen', 'Nerv', 'Snooze']],
    ['Küchenwaage', ['Gramm', 'Backen', 'klein']],
    ['Personenwaage', ['Morgen', 'Bad', 'Zahl']],
    ['Thermometer', ['Fieber', 'Stirn', 'krank']],
    ['Hausapotheke', ['Schrank', 'Pflaster', 'Tabletten']],
    ['Pflaster', ['Knie', 'Kind', 'bunt']],
    ['Verband', ['Mull', 'wickeln', 'Wunde']],
    ['Klopapier', ['Rolle', 'Bad', 'Vorrat']],
    ['Küchenrolle', ['Halter', 'wischen', 'reißen']],
    ['Taschentücher', ['Nase', 'Päckchen', 'Erkältung']],
    ['Zahnbürste', ['Bad', 'Morgen', 'Borsten']],
    ['Zahnpasta', ['Tube', 'Minze', 'weiß']],
    ['Zahnseide', ['Faden', 'zwischen', 'Pflicht']],
    ['Mundwasser', ['gurgeln', 'Flasche', 'Minze']],
    ['Duschgel', ['Flasche', 'Dusche', 'Duft']],
    ['Shampoo', ['Haare', 'Flasche', 'Schaum']],
    ['Conditioner', ['nach', 'Haare', 'glatt']],
    ['Seife', ['Stück', 'Hände', 'Schaum']],
    ['Handtuch', ['Haken', 'Bad', 'trocknen']],
    ['Badematte', ['Füße', 'nass', 'weich']],
    ['Duschvorhang', ['Stange', 'Haken', 'Plastik']],
    ['Föhn', ['Haare', 'laut', 'heiß']],
    ['Glätteisen', ['Haare', 'heiß', 'Platten']],
    ['Lockenstab', ['Haare', 'Wellen', 'Hitze']],
    ['Rasierer', ['Klinge', 'Schaum', 'Bad']],
    ['Deodorant', ['Achsel', 'Spray', 'Morgen']],
    ['Parfüm', ['Flakon', 'Duft', 'Nacken']],
    ['Sonnencreme', ['Strand', 'fettig', 'weiß']],
    ['Handcreme', ['Winter', 'trocken', 'Tube']],
    ['Bettwäsche', ['frisch', 'waschen', 'Muster']],
    ['Kopfkissen', ['weich', 'Kopf', 'Schlaf']],
    ['Decke', ['warm', 'Winter', 'kuschelig']],
    ['Matratze', ['Bett', 'fest', 'Rücken']],
    ['Bettdecke', ['Feder', 'Winter', 'Bezug']],
    ['Bettbezug', ['Knöpfe', 'Waschen', 'wechseln']],
    ['Spannbettlaken', ['Ecken', 'straff', 'Farbe']],
    ['Sofa', ['Wohnzimmer', 'Fernsehen', 'Kissen']],
    ['Sessel', ['Ecke', 'Lesen', 'gemütlich']],
    ['Hocker', ['klein', 'flexibel', 'Sitzen']],
    ['Couchtisch', ['Wohnzimmer', 'flach', 'Fernbedienung']],
    ['Esstisch', ['Familie', 'sechs', 'Holz']],
    ['Stuhl', ['vier Beine', 'Lehne', 'sitzen']],
    ['Bank', ['Flur', 'Garten', 'sitzen']],
    ['Schreibtisch', ['Laptop', 'Arbeit', 'Licht']],
    ['Bürostuhl', ['Rollen', 'Lehne', 'verstellbar']],
    ['Kleiderschrank', ['Bügel', 'Schlafzimmer', 'Tür']],
    ['Kommode', ['Schubladen', 'Schlafzimmer', 'Socken']],
    ['Regal', ['Bretter', 'Bücher', 'Wand']],
    ['Bücherregal', ['Wohnzimmer', 'Reihe', 'staubig']],
    ['Kleiderbügel', ['Schrank', 'hängen', 'Plastik']],
    ['Wäschekorb', ['schmutzig', 'voll', 'Keller']],
    ['Wäscheständer', ['Küche', 'trocknen', 'klappbar']],
    ['Bügelbrett', ['hoch', 'ausklappen', 'Keller']],
    ['Bügelwäsche', ['Korb', 'Stapel', 'Ärger']],
    ['Teppich', ['weich', 'Wohnzimmer', 'Staub']],
    ['Fußmatte', ['Eingang', 'Schuhe', 'Willkommen']],
    ['Vorhang', ['Fenster', 'Sonne', 'Stange']],
    ['Gardine', ['Fenster', 'weiß', 'durchscheinend']],
    ['Rollo', ['Fenster', 'ziehen', 'Dunkelheit']],
    ['Jalousie', ['Lamellen', 'Fenster', 'Licht']],
    ['Klingel', ['Tür', 'Besuch', 'laut']],
    ['Türschloss', ['Schlüssel', 'drehen', 'Sicherheit']],
    ['Schlüsselbund', ['klimpern', 'Hosentasche', 'Karabiner']],
    ['Briefkasten', ['Post', 'Werbung', 'Nummer']],
    ['Fußabtreter', ['Eingang', 'Hallo', 'dreckig']],
    ['Garderobe', ['Haken', 'Flur', 'Jacke']],
    ['Schuhregal', ['Flur', 'aufgereiht', 'Paar']],
    ['Abstellkammer', ['Kram', 'klein', 'vergessen']],
    ['Dachboden', ['Kisten', 'Staub', 'alt']],
    ['Keller', ['kühl', 'Vorrat', 'Treppe']],
    ['Balkon', ['Sommer', 'Stühle', 'Blumen']],
    ['Terrasse', ['Garten', 'Stein', 'Grill']],
    ['Grill', ['Sommer', 'Kohle', 'Fleisch']],
    ['Gartenstuhl', ['klappbar', 'Balkon', 'Sonne']],
    ['Hängematte', ['Bäume', 'schaukeln', 'Urlaub']],
    ['Pool', ['Garten', 'Sommer', 'Planschen']],
    ['Planschbecken', ['Kind', 'Garten', 'Sommer']],
    ['Sonnenschirm', ['Schatten', 'Balkon', 'groß']],
    ['Sonnenbrille', ['Sommer', 'Gläser', 'cool']],
    ['Regenschirm', ['Bus', 'vergessen', 'nass']],
    ['Regenjacke', ['Kapuze', 'wasserdicht', 'Herbst']],
    ['Gummistiefel', ['Pfütze', 'Regen', 'Kind']],
    ['Fahrradhelm', ['Kopf', 'Schnalle', 'Sicherheit']],
    ['Rucksack', ['Schultern', 'Schule', 'Ausflug']],
    ['Einkaufstasche', ['Supermarkt', 'Stoff', 'Henkel']],
    ['Einkaufszettel', ['vergessen', 'Kühlschrank', 'Liste']],
    ['Geldbörse', ['Karten', 'Hosentasche', 'Münzen']],
  ],

  // ==========================================================================
  'Dies und Das': [
    ['Regenbogen', ['nach Regen', 'bunt', 'Kinderbuch']],
    ['Blitz', ['Gewitter', 'kurz', 'Angst']],
    ['Donner', ['grollen', 'nach Blitz', 'fern']],
    ['Nebel', ['Morgen', 'dicht', 'mystisch']],
    ['Schatten', ['Sonne', 'Boden', 'folgen']],
    ['Echo', ['Berg', 'wiederholen', 'Halle']],
    ['Stille', ['Nacht', 'tief', 'Wald']],
    ['Fernweh', ['Karte', 'Flughafen', 'Herbst']],
    ['Heimweh', ['Urlaub', 'abends', 'Familie']],
    ['Déjà-vu', ['Moment', 'Gefühl', 'seltsam']],
    ['Glück', ['lächeln', 'Moment', 'schwer']],
    ['Neid', ['Nachbar', 'grün', 'still']],
    ['Stolz', ['Kind', 'Medaille', 'aufrecht']],
    ['Langeweile', ['Wartezimmer', 'Seufzen', 'Uhr']],
    ['Panik', ['Herz', 'Hände', 'plötzlich']],
    ['Schüchternheit', ['Ecke', 'erröten', 'Worte']],
    ['Verliebtheit', ['Schmetterlinge', 'Gedanken', 'lächeln']],
    ['Eifersucht', ['Blick', 'still', 'grün']],
    ['Geduld', ['warten', 'Uhr', 'Erwachsene']],
    ['Vertrauen', ['fallen lassen', 'Augen zu', 'Jahre']],
    ['Lüge', ['klein', 'Notlüge', 'Mutter']],
    ['Geheimnis', ['zwei Personen', 'flüstern', 'Grab']],
    ['Versprechen', ['kleiner Finger', 'halten', 'brechen']],
    ['Entschuldigung', ['peinlich', 'ehrlich', 'Blumen']],
    ['Kompliment', ['rot werden', 'Lächeln', 'ehrlich']],
    ['Trinkgeld', ['Taxi', 'Restaurant', 'runden']],
    ['Mitternacht', ['Silvester', 'still', 'Geister']],
    ['Sonnenaufgang', ['Strand', 'früh', 'orange']],
    ['Sonnenuntergang', ['Terrasse', 'Instagram', 'romantisch']],
    ['Vollmond', ['klar', 'Werwolf', 'Schlaflos']],
    ['Sternschnuppe', ['Wunsch', 'August', 'schnell']],
    ['Polarlicht', ['Norden', 'grün', 'Foto']],
    ['Komet', ['lang', 'selten', 'Teleskop']],
    ['Meteor', ['Krater', 'Dinosaurier', 'schnell']],
    ['Galaxie', ['Spirale', 'Milchstraße', 'Nacht']],
    ['Schwarzes Loch', ['All', 'Einstein', 'schlucken']],
    ['Wurmloch', ['Science Fiction', 'Abkürzung', 'Theorie']],
    ['Urknall', ['Anfang', 'Theorie', 'All']],
    ['Evolution', ['Darwin', 'Millionen', 'Anpassung']],
    ['Gravitation', ['Apfel', 'Newton', 'unten']],
    ['Schwerelosigkeit', ['All', 'schweben', 'Astronaut']],
    ['Magnetismus', ['Kühlschrank', 'Pol', 'ziehen']],
    ['Elektrizität', ['Stecker', 'Funke', 'Leitung']],
    ['Regen', ['grau', 'Herbst', 'Schirm']],
    ['Schnee', ['Flocken', 'weiß', 'Winter']],
    ['Hagel', ['Auto', 'Dach', 'schnell']],
    ['Eiszapfen', ['Dach', 'spitz', 'Winter']],
    ['Lawine', ['Berg', 'Skifahrer', 'rasch']],
    ['Erdbeben', ['wackeln', 'Richter', 'plötzlich']],
    ['Vulkan', ['Lava', 'Ausbruch', 'Rauch']],
    ['Tsunami', ['Welle', 'Warnung', 'Küste']],
    ['Wirbelsturm', ['Dorothy', 'Trichter', 'zerstören']],
    ['Flut', ['Mond', 'Küste', 'Kanäle']],
    ['Ebbe', ['leer', 'Küste', 'Muscheln']],
    ['Dschungel', ['Lianen', 'schwül', 'Affen']],
    ['Wüste', ['Kamel', 'Sand', 'Oase']],
    ['Savanne', ['Löwen', 'Afrika', 'Gras']],
    ['Tundra', ['kalt', 'flach', 'Moos']],
    ['Polarmeer', ['Eis', 'Bären', 'kalt']],
    ['Koralle', ['Riff', 'bunt', 'Taucher']],
    ['Vulkaninsel', ['entstehen', 'Hawaii', 'rund']],
    ['Höhle', ['dunkel', 'Fledermäuse', 'Tropfstein']],
    ['Schlucht', ['tief', 'Grand Canyon', 'Echo']],
    ['Wasserfall', ['Niagara', 'Gischt', 'Lärm']],
    ['Geysir', ['Island', 'heiß', 'hoch']],
    ['Moor', ['weich', 'Nebel', 'Leichen']],
    ['Sumpf', ['Alligator', 'schlammig', 'dunkel']],
    ['Oase', ['Palmen', 'Wüste', 'Wasser']],
    ['Fjord', ['Norwegen', 'tief', 'Kreuzfahrt']],
    ['Gletscher', ['schmelzen', 'blau', 'langsam']],
    ['Meteoritenkrater', ['rund', 'Wüste', 'Jahrtausende']],
    ['Teleskop', ['Sterne', 'Hobby', 'Linse']],
    ['Mikroskop', ['Schule', 'klein', 'Präparat']],
    ['Roboter', ['Zukunft', 'Metall', 'piepen']],
    ['Drohne', ['Hochzeit', 'summen', 'Kamera']],
    ['Satellit', ['Umlauf', 'TV', 'klein']],
    ['U-Boot', ['Tiefe', 'Periskop', 'eng']],
    ['Raumschiff', ['Star Trek', 'All', 'Zukunft']],
    ['Rakete', ['Start', 'Countdown', 'Rauch']],
    ['Zeppelin', ['Hindenburg', 'lang', 'Geschichte']],
    ['Heißluftballon', ['Korb', 'Feuer', 'Fest']],
    ['Flaschenpost', ['Meer', 'Geheimnis', 'Strand']],
    ['Papierflieger', ['Schule', 'werfen', 'weich']],
    ['Drachen', ['Wind', 'Schnur', 'Herbst']],
    ['Yo-Yo', ['90er', 'Finger', 'hoch runter']],
    ['Kaleidoskop', ['bunt', 'drehen', 'Spiegel']],
    ['Zauberwürfel', ['bunt', 'Ungeduld', '80er']],
    ['Puzzle', ['Teile', 'Tisch', 'Abend']],
    ['Kreuzworträtsel', ['Zeitung', 'Stift', 'Oma']],
    ['Sudoku', ['Zahlen', 'Zug', 'Gehirn']],
    ['Tagebuch', ['Schloss', 'Teenager', 'Gefühle']],
    ['Glückskeks', ['Zettel', 'China', 'Dessert']],
    ['Schatzkarte', ['X', 'Pirat', 'alt']],
    ['Kompass', ['Norden', 'Nadel', 'Wandern']],
    ['Sanduhr', ['rinnen', 'Zeit', 'Brettspiel']],
    ['Pendel', ['Uhr', 'Hypnose', 'schwingen']],
    ['Metronom', ['Takt', 'Klavier', 'Üben']],
    ['Stimmgabel', ['Ton', 'Musiker', 'Metall']],
    ['Kerzenständer', ['romantisch', 'Tisch', 'Silber']],
    ['Wanduhr', ['Küche', 'ticken', 'Zeiger']],
    ['Taschenuhr', ['Großvater', 'Kette', 'antik']],
    ['Brosche', ['Großmutter', 'Oma', 'Blumen']],
    ['Medaille', ['Podium', 'Band', 'Bronze']],
    ['Pokal', ['Sieg', 'Regal', 'glänzen']],
    ['Urkunde', ['Rahmen', 'Wand', 'Leistung']],
    ['Stammbaum', ['Familie', 'Äste', 'Geschichte']],
    ['Fotoalbum', ['alt', 'Erinnerung', 'Dachboden']],
    ['Liebesbrief', ['parfümiert', 'Herz', 'versteckt']],
    ['Postkarte', ['Urlaub', 'kurz', 'Briefkasten']],
    ['Stempel', ['Amt', 'rot', 'wichtig']],
    ['Briefmarke', ['Sammler', 'klein', 'Urlaub']],
    ['Reliquie', ['Museum', 'heilig', 'alt']],
    ['Schatz', ['Kiste', 'Gold', 'Pirat']],
    ['Fluch', ['Mumie', 'Jahrhunderte', 'Angst']],
    ['Aberglaube', ['Leiter', 'Spiegel', 'Freitag']],
    ['Horoskop', ['Zeitung', 'Sterne', 'Zeichen']],
    ['Ouija-Brett', ['Geister', 'gruselig', 'Keller']],
    ['Kristallkugel', ['Wahrsagerin', 'trüb', 'Zukunft']],
    ['Tarotkarten', ['Tisch', 'Symbole', 'deuten']],
    ['Handlinie', ['Lesen', 'Zukunft', 'Hand']],
    ['Glückszahl', ['sieben', 'Lotto', 'Geburtstag']],
    ['Talisman', ['tragen', 'Glück', 'klein']],
    ['Kleeblatt', ['vierblättrig', 'Glück', 'Wiese']],
    ['Hufeisen', ['Tür', 'Glück', 'Pferd']],
    ['Marienkäfer', ['rot', 'Punkte', 'Glück']],
    ['Schornsteinfeger', ['schwarz', 'Dach', 'Glück']],
    ['Schornstein', ['Rauch', 'Dach', 'Weihnachtsmann']],
    ['Wunschbrunnen', ['Münze', 'Innenhof', 'Wunsch']],
    ['Geburtstagstorte', ['Kerzen', 'Wunsch', 'pusten']],
    ['Adventskalender', ['24', 'Türchen', 'Schoki']],
    ['Weihnachtsbaum', ['Nadeln', 'Kugeln', 'Wohnzimmer']],
    ['Osterei', ['bunt', 'suchen', 'Garten']],
    ['Karneval', ['Maske', 'Helau', 'Kostüm']],
    ['Silvesterkracher', ['Mitternacht', 'knallen', 'verboten']],
    ['Feuerwerk', ['Himmel', 'bunt', 'Fest']],
    ['Konfetti', ['Party', 'werfen', 'Teppich']],
    ['Luftschlange', ['Karneval', 'bunt', 'pusten']],
    ['Geburtstagsgeschenk', ['Schleife', 'Spannung', 'auspacken']],
    ['Überraschung', ['Augen zu', 'Schock', 'Freude']],
    ['Witz', ['Pointe', 'lachen', 'Opa']],
    ['Peinlichkeit', ['Schule', 'Erinnerung', 'erröten']],
    ['Skandal', ['Zeitung', 'Promi', 'geflüstert']],
    ['Gerücht', ['weitergeben', 'Nachbarn', 'Küche']],
    ['Klatsch', ['Kaffee', 'Frauen', 'andere']],
    ['Tratsch', ['Dorf', 'Bäcker', 'lang']],
    ['Schlagzeile', ['fett', 'morgens', 'Zeitung']],
    ['Liveübertragung', ['Moderator', 'Studio', 'draußen']],
    ['Applaus', ['Bühne', 'Vorhang', 'stehend']],
    ['Standing Ovations', ['Theater', 'aufstehen', 'Künstler']],
    ['Zugabe', ['Konzert', 'rufen', 'klatschen']],
    ['Premiere', ['rot', 'Kamera', 'Gäste']],
    ['Vernissage', ['Wein', 'Kunst', 'klein']],
    ['Abschlussball', ['Kleid', 'Musik', 'letzter Tag']],
    ['Hochzeit', ['weiß', 'Jawort', 'Tränen']],
    ['Beerdigung', ['schwarz', 'Kranz', 'still']],
    ['Taufe', ['Pate', 'Wasser', 'Baby']],
    ['Kommunion', ['weiß', 'Kirche', 'Geschenke']],
    ['Abitur', ['Feier', 'Zeugnis', 'Freiheit']],
    ['Rente', ['Garten', 'Zeit', 'Enkel']],
    ['Jubiläum', ['Firma', 'Rede', 'Sekt']],
  ],
};

// ============================================================================
// Utility: Flacht alle Wörter aus und liefert alle eindeutigen Hauptwörter zurück
// ============================================================================
export const getAllWordsFromCategories = (categories: Category[]): WordEntry[] => {
  const pool: WordEntry[] = [];
  categories.forEach(cat => {
    if (WORD_PACKS[cat]) {
      WORD_PACKS[cat].forEach(([word, associations]) => {
        pool.push({ word, associations, category: cat });
      });
    }
  });
  return pool;
};
